// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "C:/Users/johannes.lauter/Documents/GitHub/initium-nuxt/packages/variant-a/app.config";
import type { default as appConfig1 } from "C:/Users/johannes.lauter/Documents/GitHub/initium-nuxt/packages/webapp/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}