packages:
  # all packages in subdirs of packages/ and apps/
  - 'packages/**'
  - 'apps/**'

catalogs:
  # Packages used for building the project (e.g., vite, rolldown).
  build:
    '@storybook/addon-a11y': 9.1.17
    '@storybook/addon-docs': 9.1.17
    '@storybook/addon-vitest': 9.1.17
    '@storybook/vue3-vite': 9.1.17
    '@tailwindcss/vite': 4.1.17
    '@vitejs/plugin-vue': 6.0.3
    storybook: 9.1.17
    unplugin-auto-import: 20.3.0
    unplugin-vue-components: 28.8.0
    vite: 7.2.4
  # Packages for frontend development (e.g., vue, pinia).
  frontend:
    '@nuxtjs/color-mode': 3.5.2
    '@pinia/nuxt': 0.11.3
    '@vue-macros/nuxt': 1.13.5
    '@vueuse/components': 13.9.0
    '@vueuse/core': 13.9.0
    '@vueuse/nuxt': 13.9.0
    autoprefixer: 10.4.23
    pinia: 3.0.4
    tailwindcss: 4.1.17
    vue: 3.5.26
  #  Packages for linting/formatting (e.g., eslint, knip).
  lint:
    '@antfu/eslint-config': 4.19.0
    eslint: 9.39.2
  # Packages that are included directly in the final bundle.
  #  inlined:
  # Runtime production dependencies.
  prod:
    '@nuxt/devtools': 2.7.0
    '@nuxt/image': 1.11.0
    '@nuxt/kit': 3.20.2
    '@nuxt/schema': 3.20.2
    nuxt: 3.20.2
  # Packages used for scripting tasks (e.g., tsx, tinyglobby, cpx).
  script:
    concurrently: 9.2.1
  # Packages used for testing (e.g., vitest, playwright, msw).
  test:
    '@nuxt/test-utils-edge': 3.8.0-28284309.b3d3d7f4
    '@storybook/test': 8.6.15
    '@vitest/browser': 3.2.4
    '@vitest/coverage-v8': 3.2.4
    playwright: 1.57.0
    vitest: 3.2.4
  # Packages for the backend server.
  #  backend:
  # Packages for type checking and definitions.
  types:
    '@tsconfig/recommended': 1.0.13
    '@vue/tsconfig': 0.8.1
    typescript: 5.9.3
    vue-tsc: 3.1.5
