packages:
  # all packages in subdirs of packages/ and apps/
  - 'packages/**'
  - 'apps/**'

catalogs:
  # Packages used for building the project (e.g., vite, rolldown).
  build:
    '@storybook/addon-a11y': 9.1.13
    '@storybook/addon-docs': 9.1.13
    '@storybook/addon-vitest': 9.1.13
    '@storybook/vue3-vite': 9.1.13
    '@tailwindcss/vite': 4.1.15
    '@vitejs/plugin-vue': 6.0.1
    storybook: 9.1.13
    unplugin-auto-import: 19.3.0
    unplugin-vue-components: 28.8.0
    vite: 7.1.11
  # Packages for frontend development (e.g., vue, pinia).
  frontend:
    '@nuxtjs/color-mode': 3.5.2
    '@pinia/nuxt': 0.11.2
    '@vue-macros/nuxt': 1.13.5
    '@vueuse/components': 13.9.0
    '@vueuse/core': 13.9.0
    '@vueuse/nuxt': 13.9.0
    autoprefixer: 10.4.21
    pinia: 3.0.3
    tailwindcss: 4.1.15
    vue: 3.5.22
  #  Packages for linting/formatting (e.g., eslint, knip).
  lint:
    '@antfu/eslint-config': 6.0.0
    eslint: 9.38.0
  # Packages that are included directly in the final bundle.
  #  inlined:
  # Runtime production dependencies.
  prod:
    '@nuxt/devtools': 2.6.5
    '@nuxt/image': 1.11.0
    '@nuxt/kit': 3.19.3
    '@nuxt/schema': 3.19.3
    nuxt: 3.19.3
  # Packages used for scripting tasks (e.g., tsx, tinyglobby, cpx).
  script:
    concurrently: 9.2.1
  # Packages used for testing (e.g., vitest, playwright, msw).
  test:
    '@nuxt/test-utils-edge': 3.8.0-28284309.b3d3d7f4
    '@storybook/test': 8.6.14
    '@vitest/browser': 3.2.4
    '@vitest/coverage-v8': 3.2.4
    playwright: 1.56.1
    vitest: 3.2.4
  # Packages for the backend server.
  #  backend:
  # Packages for type checking and definitions.
  types:
    '@tsconfig/recommended': 1.0.10
    '@vue/tsconfig': 0.8.1
    typescript: 5.9.3
    vue-tsc: 3.1.1
