// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/Button.vue')['default']
    Input: typeof import('./components/ui/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./components/interaction/SignIn.vue')['default']
    UiButton: typeof import('~/components/ui/Button.vue')['default']
    UiInput: typeof import('~/components/ui/Input.vue')['default']
  }
}
