/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    InteractionSignIn: typeof import('./components/interaction/SignIn.vue')['default']
    LayoutApplication: typeof import('./components/layout/Application.vue')['default']
    LayoutSplash: typeof import('./components/layout/Splash.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./components/ui/Button.vue')['default']
    UiInput: typeof import('./components/ui/Input.vue')['default']
    UiSheet: typeof import('./components/ui/Sheet.vue')['default']
  }
}
